spring:
  rabbitmq:
    username: admin
    password: admin
    host: 127.0.0.1
    virtual-host: /
    port: 5672
    publisher-confirms: true 
server:
  port: 8081
logging:
  path: D:\log
  pattern:
    level: ERROR
